#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2014 Rohan Garg <rohan@kde.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/guacamole-tomcat.list ] || \
	   [ -e /var/lib/live/config/guacamole ]
	then
		exit 0
	fi

	echo -n " guacamole"
}

Config ()
{

cat > /etc/guacamole/user-mapping.xml << EOF
<user-mapping>
<authorize username="${LIVE_USERNAME}" password="${LIVE_USERNAME}">
<protocol>vnc</protocol>
<param name="hostname">localhost</param>
<param name="port">5900</param>
<param name="password">"${LIVE_USERNAME}"</param>
</authorize>
</user-mapping>
EOF

	# Creating state file
	touch /var/lib/live/config/guacamole
}

Cmdline
Init
Config
